<?xml version="1.0" encoding="utf-8"?><Database Name="tcTHEBUS" Class="dbTradeControlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IAM;Initial Catalog=tcTHEBUS;Integrated Security=True" SettingsObjectName="TradeControl.Tax.Office.Properties.Settings" SettingsPropertyName="tcTHEBUSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Cash.vwTaxVatTotals" Member="vwTaxVatTotals">
    <Type Name="vwTaxVatTotal">
      <Column Name="YearNumber" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StartOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HomeSales" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="HomePurchases" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="ExportSales" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="ExportPurchases" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="HomeSalesVat" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="HomePurchasesVat" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="ExportSalesVat" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="ExportPurchasesVat" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="VatAdjustment" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
      <Column Name="VatDue" Type="System.Decimal" DbType="Decimal(38,5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>