//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeControl.Tax.Office.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeControl.Tax.Office.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection string has been specified (ConnectionString).
        /// </summary>
        internal static string ConnectionStringUnspecified {
            get {
                return ResourceManager.GetString("ConnectionStringUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value of EC purchases, excluding VAT.
        /// </summary>
        internal static string ExportPurchases {
            get {
                return ResourceManager.GetString("ExportPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value of EC sales, excluding VAT.
        /// </summary>
        internal static string ExportSales {
            get {
                return ResourceManager.GetString("ExportSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT due in this period on EC acquisitions.
        /// </summary>
        internal static string ExportSalesVat {
            get {
                return ResourceManager.GetString("ExportSalesVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT reclaimed in this period on purchases.
        /// </summary>
        internal static string HomePurchasesVat {
            get {
                return ResourceManager.GetString("HomePurchasesVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT due in this period on sales.
        /// </summary>
        internal static string HomeSalesVat {
            get {
                return ResourceManager.GetString("HomeSalesVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify CSV export file name.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total VAT due (sum of boxes 1 and 2).
        /// </summary>
        internal static string SalesVatDue {
            get {
                return ResourceManager.GetString("SalesVatDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value of purchases, excluding VAT.
        /// </summary>
        internal static string TotalPurchases {
            get {
                return ResourceManager.GetString("TotalPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value of sales, excluding VAT.
        /// </summary>
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net VAT to be paid to Customs or reclaimed by you.
        /// </summary>
        internal static string VatDue {
            get {
                return ResourceManager.GetString("VatDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Period cannot be located.
        /// </summary>
        internal static string VatPeriodNotFound {
            get {
                return ResourceManager.GetString("VatPeriodNotFound", resourceCulture);
            }
        }
    }
}
