//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeControl.CashFlow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeControl.CashFlow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUDGET PERFORMANCE - {0} {1} .
        /// </summary>
        internal static string BudgetStatementTitle {
            get {
                return ResourceManager.GetString("BudgetStatementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server cannot be established.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,##0_);[Red](#,##0).
        /// </summary>
        internal static string FormatNumber {
            get {
                return ResourceManager.GetString("FormatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        internal static string FormatPercent {
            get {
                return ResourceManager.GetString("FormatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of worksheet has failed. Consult the error log for details..
        /// </summary>
        internal static string GenerationFailed {
            get {
                return ResourceManager.GetString("GenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYSIS.
        /// </summary>
        internal static string TextAnalysis {
            get {
                return ResourceManager.GetString("TextAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSING BALANCE.
        /// </summary>
        internal static string TextClosingBalances {
            get {
                return ResourceManager.GetString("TextClosingBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string TextCode {
            get {
                return ResourceManager.GetString("TextCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Balance.
        /// </summary>
        internal static string TextCompanyBalance {
            get {
                return ResourceManager.GetString("TextCompanyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string TextDate {
            get {
                return ResourceManager.GetString("TextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERIOD TOTAL.
        /// </summary>
        internal static string TextPeriodTotal {
            get {
                return ResourceManager.GetString("TextPeriodTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADE STATEMENT - {0} {1}.
        /// </summary>
        internal static string TextStatementTitle {
            get {
                return ResourceManager.GetString("TextStatementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY.
        /// </summary>
        internal static string TextSummary {
            get {
                return ResourceManager.GetString("TextSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTALS.
        /// </summary>
        internal static string TextTotals {
            get {
                return ResourceManager.GetString("TextTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Adjustments.
        /// </summary>
        internal static string TextVatAdjustment {
            get {
                return ResourceManager.GetString("TextVatAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT DUE.
        /// </summary>
        internal static string TextVatDue {
            get {
                return ResourceManager.GetString("TextVatDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string TextVatDueTitle {
            get {
                return ResourceManager.GetString("TextVatDueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Purchases.
        /// </summary>
        internal static string TextVatExportPurchases {
            get {
                return ResourceManager.GetString("TextVatExportPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Purchases Vat.
        /// </summary>
        internal static string TextVatExportPurchasesVat {
            get {
                return ResourceManager.GetString("TextVatExportPurchasesVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Sales.
        /// </summary>
        internal static string TextVatExportSales {
            get {
                return ResourceManager.GetString("TextVatExportSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Sales Vat.
        /// </summary>
        internal static string TextVatExportSalesVat {
            get {
                return ResourceManager.GetString("TextVatExportSalesVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Purchases.
        /// </summary>
        internal static string TextVatHomePurchases {
            get {
                return ResourceManager.GetString("TextVatHomePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Purchases Vat.
        /// </summary>
        internal static string TextVatHomePurchasesVat {
            get {
                return ResourceManager.GetString("TextVatHomePurchasesVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Sales.
        /// </summary>
        internal static string TextVatHomeSales {
            get {
                return ResourceManager.GetString("TextVatHomeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Sales Vat.
        /// </summary>
        internal static string TextVatHomeSalesVat {
            get {
                return ResourceManager.GetString("TextVatHomeSalesVat", resourceCulture);
            }
        }
    }
}
