#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeControl.Documents.Word
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tcTHEBUS")]
	public partial class dbTradeControlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbAttribute(tbAttribute instance);
    partial void UpdatetbAttribute(tbAttribute instance);
    partial void DeletetbAttribute(tbAttribute instance);
    partial void InserttbDocType(tbDocType instance);
    partial void UpdatetbDocType(tbDocType instance);
    partial void DeletetbDocType(tbDocType instance);
    partial void InserttbQuote(tbQuote instance);
    partial void UpdatetbQuote(tbQuote instance);
    partial void DeletetbQuote(tbQuote instance);
    partial void InserttbOp(tbOp instance);
    partial void UpdatetbOp(tbOp instance);
    partial void DeletetbOp(tbOp instance);
    #endregion
		
		public dbTradeControlDataContext() : 
				base(global::TradeControl.Documents.Word.Properties.Settings.Default.tcTHEBUSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbTradeControlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTradeControlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTradeControlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTradeControlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbAttribute> tbAttributes
		{
			get
			{
				return this.GetTable<tbAttribute>();
			}
		}
		
		public System.Data.Linq.Table<vwDocInvoiceItem> vwDocInvoiceItems
		{
			get
			{
				return this.GetTable<vwDocInvoiceItem>();
			}
		}
		
		public System.Data.Linq.Table<vwTaxSummary> vwTaxSummaries
		{
			get
			{
				return this.GetTable<vwTaxSummary>();
			}
		}
		
		public System.Data.Linq.Table<vwDocCompany> vwDocCompanies
		{
			get
			{
				return this.GetTable<vwDocCompany>();
			}
		}
		
		public System.Data.Linq.Table<tbDocType> tbDocTypes
		{
			get
			{
				return this.GetTable<tbDocType>();
			}
		}
		
		public System.Data.Linq.Table<vwDocInvoice> vwDocInvoices
		{
			get
			{
				return this.GetTable<vwDocInvoice>();
			}
		}
		
		public System.Data.Linq.Table<tbQuote> tbQuotes
		{
			get
			{
				return this.GetTable<tbQuote>();
			}
		}
		
		public System.Data.Linq.Table<tbOp> tbOps
		{
			get
			{
				return this.GetTable<tbOp>();
			}
		}
		
		public System.Data.Linq.Table<vwDocTaskCode> vwDocTaskCodes
		{
			get
			{
				return this.GetTable<vwDocTaskCode>();
			}
		}
		
		public System.Data.Linq.Table<vwDocInvoiceTask> vwDocInvoiceTasks
		{
			get
			{
				return this.GetTable<vwDocInvoiceTask>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Task.proc_Op")]
		public ISingleResult<proc_OpResult> proc_Op([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaskCode", DbType="NVarChar(20)")] string taskCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taskCode);
			return ((ISingleResult<proc_OpResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Task.tbAttribute")]
	public partial class tbAttribute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaskCode;
		
		private string _Attribute;
		
		private short _PrintOrder;
		
		private short _AttributeTypeCode;
		
		private string _AttributeDescription;
		
		private string _InsertedBy;
		
		private System.DateTime _InsertedOn;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskCodeChanging(string value);
    partial void OnTaskCodeChanged();
    partial void OnAttributeChanging(string value);
    partial void OnAttributeChanged();
    partial void OnPrintOrderChanging(short value);
    partial void OnPrintOrderChanged();
    partial void OnAttributeTypeCodeChanging(short value);
    partial void OnAttributeTypeCodeChanged();
    partial void OnAttributeDescriptionChanging(string value);
    partial void OnAttributeDescriptionChanged();
    partial void OnInsertedByChanging(string value);
    partial void OnInsertedByChanged();
    partial void OnInsertedOnChanging(System.DateTime value);
    partial void OnInsertedOnChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tbAttribute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaskCode
		{
			get
			{
				return this._TaskCode;
			}
			set
			{
				if ((this._TaskCode != value))
				{
					this.OnTaskCodeChanging(value);
					this.SendPropertyChanging();
					this._TaskCode = value;
					this.SendPropertyChanged("TaskCode");
					this.OnTaskCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attribute", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Attribute
		{
			get
			{
				return this._Attribute;
			}
			set
			{
				if ((this._Attribute != value))
				{
					this.OnAttributeChanging(value);
					this.SendPropertyChanging();
					this._Attribute = value;
					this.SendPropertyChanged("Attribute");
					this.OnAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintOrder", DbType="SmallInt NOT NULL")]
		public short PrintOrder
		{
			get
			{
				return this._PrintOrder;
			}
			set
			{
				if ((this._PrintOrder != value))
				{
					this.OnPrintOrderChanging(value);
					this.SendPropertyChanging();
					this._PrintOrder = value;
					this.SendPropertyChanged("PrintOrder");
					this.OnPrintOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeTypeCode", DbType="SmallInt NOT NULL")]
		public short AttributeTypeCode
		{
			get
			{
				return this._AttributeTypeCode;
			}
			set
			{
				if ((this._AttributeTypeCode != value))
				{
					this.OnAttributeTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._AttributeTypeCode = value;
					this.SendPropertyChanged("AttributeTypeCode");
					this.OnAttributeTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeDescription", DbType="NVarChar(512)")]
		public string AttributeDescription
		{
			get
			{
				return this._AttributeDescription;
			}
			set
			{
				if ((this._AttributeDescription != value))
				{
					this.OnAttributeDescriptionChanging(value);
					this.SendPropertyChanging();
					this._AttributeDescription = value;
					this.SendPropertyChanged("AttributeDescription");
					this.OnAttributeDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this.OnInsertedByChanging(value);
					this.SendPropertyChanging();
					this._InsertedBy = value;
					this.SendPropertyChanged("InsertedBy");
					this.OnInsertedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InsertedOn
		{
			get
			{
				return this._InsertedOn;
			}
			set
			{
				if ((this._InsertedOn != value))
				{
					this.OnInsertedOnChanging(value);
					this.SendPropertyChanging();
					this._InsertedOn = value;
					this.SendPropertyChanged("InsertedOn");
					this.OnInsertedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Invoice.vwDocItem")]
	public partial class vwDocInvoiceItem
	{
		
		private string _InvoiceNumber;
		
		private string _CashCode;
		
		private string _CashDescription;
		
		private System.DateTime _ActionedOn;
		
		private string _TaxCode;
		
		private decimal _InvoiceValue;
		
		private decimal _TaxValue;
		
		private string _ItemReference;
		
		public vwDocInvoiceItem()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CashCode
		{
			get
			{
				return this._CashCode;
			}
			set
			{
				if ((this._CashCode != value))
				{
					this._CashCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashDescription", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CashDescription
		{
			get
			{
				return this._CashDescription;
			}
			set
			{
				if ((this._CashDescription != value))
				{
					this._CashDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ActionedOn
		{
			get
			{
				return this._ActionedOn;
			}
			set
			{
				if ((this._ActionedOn != value))
				{
					this._ActionedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValue", DbType="Money NOT NULL")]
		public decimal InvoiceValue
		{
			get
			{
				return this._InvoiceValue;
			}
			set
			{
				if ((this._InvoiceValue != value))
				{
					this._InvoiceValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValue", DbType="Money NOT NULL")]
		public decimal TaxValue
		{
			get
			{
				return this._TaxValue;
			}
			set
			{
				if ((this._TaxValue != value))
				{
					this._TaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemReference", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ItemReference
		{
			get
			{
				return this._ItemReference;
			}
			set
			{
				if ((this._ItemReference != value))
				{
					this._ItemReference = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Invoice.vwTaxSummary")]
	public partial class vwTaxSummary
	{
		
		private string _InvoiceNumber;
		
		private string _TaxCode;
		
		private System.Nullable<decimal> _InvoiceValueTotal;
		
		private System.Nullable<decimal> _TaxValueTotal;
		
		private System.Nullable<decimal> _TaxRate;
		
		public vwTaxSummary()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValueTotal", DbType="Money")]
		public System.Nullable<decimal> InvoiceValueTotal
		{
			get
			{
				return this._InvoiceValueTotal;
			}
			set
			{
				if ((this._InvoiceValueTotal != value))
				{
					this._InvoiceValueTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValueTotal", DbType="Money")]
		public System.Nullable<decimal> TaxValueTotal
		{
			get
			{
				return this._TaxValueTotal;
			}
			set
			{
				if ((this._TaxValueTotal != value))
				{
					this._TaxValueTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Money")]
		public System.Nullable<decimal> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this._TaxRate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Usr.vwDoc")]
	public partial class vwDocCompany
	{
		
		private string _CompanyName;
		
		private string _CompanyAddress;
		
		private string _CompanyPhoneNumber;
		
		private string _CompanyEmailAddress;
		
		private string _CompanyWebsite;
		
		private string _CompanyNumber;
		
		private string _VatNumber;
		
		private System.Data.Linq.Binary _Logo;
		
		private string _BankAccount;
		
		private string _BankAccountNumber;
		
		private string _BankSortCode;
		
		public vwDocCompany()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyAddress", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CompanyAddress
		{
			get
			{
				return this._CompanyAddress;
			}
			set
			{
				if ((this._CompanyAddress != value))
				{
					this._CompanyAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyPhoneNumber", DbType="NVarChar(50)")]
		public string CompanyPhoneNumber
		{
			get
			{
				return this._CompanyPhoneNumber;
			}
			set
			{
				if ((this._CompanyPhoneNumber != value))
				{
					this._CompanyPhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyEmailAddress", DbType="NVarChar(255)")]
		public string CompanyEmailAddress
		{
			get
			{
				return this._CompanyEmailAddress;
			}
			set
			{
				if ((this._CompanyEmailAddress != value))
				{
					this._CompanyEmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyWebsite", DbType="NVarChar(255)")]
		public string CompanyWebsite
		{
			get
			{
				return this._CompanyWebsite;
			}
			set
			{
				if ((this._CompanyWebsite != value))
				{
					this._CompanyWebsite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyNumber", DbType="NVarChar(20)")]
		public string CompanyNumber
		{
			get
			{
				return this._CompanyNumber;
			}
			set
			{
				if ((this._CompanyNumber != value))
				{
					this._CompanyNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatNumber", DbType="NVarChar(50)")]
		public string VatNumber
		{
			get
			{
				return this._VatNumber;
			}
			set
			{
				if ((this._VatNumber != value))
				{
					this._VatNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this._Logo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccount", DbType="NVarChar(306)")]
		public string BankAccount
		{
			get
			{
				return this._BankAccount;
			}
			set
			{
				if ((this._BankAccount != value))
				{
					this._BankAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountNumber", DbType="NVarChar(20)")]
		public string BankAccountNumber
		{
			get
			{
				return this._BankAccountNumber;
			}
			set
			{
				if ((this._BankAccountNumber != value))
				{
					this._BankAccountNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankSortCode", DbType="NVarChar(10)")]
		public string BankSortCode
		{
			get
			{
				return this._BankSortCode;
			}
			set
			{
				if ((this._BankSortCode != value))
				{
					this._BankSortCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="App.tbDocType")]
	public partial class tbDocType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _DocTypeCode;
		
		private string _DocType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDocTypeCodeChanging(short value);
    partial void OnDocTypeCodeChanged();
    partial void OnDocTypeChanging(string value);
    partial void OnDocTypeChanged();
    #endregion
		
		public tbDocType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeCode", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short DocTypeCode
		{
			get
			{
				return this._DocTypeCode;
			}
			set
			{
				if ((this._DocTypeCode != value))
				{
					this.OnDocTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._DocTypeCode = value;
					this.SendPropertyChanged("DocTypeCode");
					this.OnDocTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DocType
		{
			get
			{
				return this._DocType;
			}
			set
			{
				if ((this._DocType != value))
				{
					this.OnDocTypeChanging(value);
					this.SendPropertyChanging();
					this._DocType = value;
					this.SendPropertyChanged("DocType");
					this.OnDocTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Invoice.vwDoc")]
	public partial class vwDocInvoice
	{
		
		private string _EmailAddress;
		
		private string _UserName;
		
		private string _AccountCode;
		
		private string _AccountName;
		
		private string _InvoiceAddress;
		
		private string _InvoiceNumber;
		
		private string _InvoiceType;
		
		private string _InvoiceStatus;
		
		private System.DateTime _InvoicedOn;
		
		private System.DateTime _DueOn;
		
		private decimal _InvoiceValue;
		
		private decimal _TaxValue;
		
		private string _PaymentTerms;
		
		private string _Notes;
		
		public vwDocInvoice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(255)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceAddress", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceAddress
		{
			get
			{
				return this._InvoiceAddress;
			}
			set
			{
				if ((this._InvoiceAddress != value))
				{
					this._InvoiceAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceType
		{
			get
			{
				return this._InvoiceType;
			}
			set
			{
				if ((this._InvoiceType != value))
				{
					this._InvoiceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatus", DbType="NVarChar(50)")]
		public string InvoiceStatus
		{
			get
			{
				return this._InvoiceStatus;
			}
			set
			{
				if ((this._InvoiceStatus != value))
				{
					this._InvoiceStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoicedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InvoicedOn
		{
			get
			{
				return this._InvoicedOn;
			}
			set
			{
				if ((this._InvoicedOn != value))
				{
					this._InvoicedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueOn", DbType="DateTime NOT NULL")]
		public System.DateTime DueOn
		{
			get
			{
				return this._DueOn;
			}
			set
			{
				if ((this._DueOn != value))
				{
					this._DueOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValue", DbType="Money NOT NULL")]
		public decimal InvoiceValue
		{
			get
			{
				return this._InvoiceValue;
			}
			set
			{
				if ((this._InvoiceValue != value))
				{
					this._InvoiceValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValue", DbType="Money NOT NULL")]
		public decimal TaxValue
		{
			get
			{
				return this._TaxValue;
			}
			set
			{
				if ((this._TaxValue != value))
				{
					this._TaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerms", DbType="NVarChar(100)")]
		public string PaymentTerms
		{
			get
			{
				return this._PaymentTerms;
			}
			set
			{
				if ((this._PaymentTerms != value))
				{
					this._PaymentTerms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Task.tbQuote")]
	public partial class tbQuote : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaskCode;
		
		private decimal _Quantity;
		
		private decimal _TotalPrice;
		
		private decimal _RunOnQuantity;
		
		private decimal _RunOnPrice;
		
		private decimal _RunBackQuantity;
		
		private decimal _RunBackPrice;
		
		private string _InsertedBy;
		
		private System.DateTime _InsertedOn;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskCodeChanging(string value);
    partial void OnTaskCodeChanged();
    partial void OnQuantityChanging(decimal value);
    partial void OnQuantityChanged();
    partial void OnTotalPriceChanging(decimal value);
    partial void OnTotalPriceChanged();
    partial void OnRunOnQuantityChanging(decimal value);
    partial void OnRunOnQuantityChanged();
    partial void OnRunOnPriceChanging(decimal value);
    partial void OnRunOnPriceChanged();
    partial void OnRunBackQuantityChanging(decimal value);
    partial void OnRunBackQuantityChanged();
    partial void OnRunBackPriceChanging(decimal value);
    partial void OnRunBackPriceChanged();
    partial void OnInsertedByChanging(string value);
    partial void OnInsertedByChanged();
    partial void OnInsertedOnChanging(System.DateTime value);
    partial void OnInsertedOnChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tbQuote()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaskCode
		{
			get
			{
				return this._TaskCode;
			}
			set
			{
				if ((this._TaskCode != value))
				{
					this.OnTaskCodeChanging(value);
					this.SendPropertyChanging();
					this._TaskCode = value;
					this.SendPropertyChanged("TaskCode");
					this.OnTaskCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal NOT NULL", IsPrimaryKey=true)]
		public decimal Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrice", DbType="Money NOT NULL")]
		public decimal TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				if ((this._TotalPrice != value))
				{
					this.OnTotalPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalPrice = value;
					this.SendPropertyChanged("TotalPrice");
					this.OnTotalPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunOnQuantity", DbType="Decimal NOT NULL")]
		public decimal RunOnQuantity
		{
			get
			{
				return this._RunOnQuantity;
			}
			set
			{
				if ((this._RunOnQuantity != value))
				{
					this.OnRunOnQuantityChanging(value);
					this.SendPropertyChanging();
					this._RunOnQuantity = value;
					this.SendPropertyChanged("RunOnQuantity");
					this.OnRunOnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunOnPrice", DbType="Money NOT NULL")]
		public decimal RunOnPrice
		{
			get
			{
				return this._RunOnPrice;
			}
			set
			{
				if ((this._RunOnPrice != value))
				{
					this.OnRunOnPriceChanging(value);
					this.SendPropertyChanging();
					this._RunOnPrice = value;
					this.SendPropertyChanged("RunOnPrice");
					this.OnRunOnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunBackQuantity", DbType="Decimal NOT NULL")]
		public decimal RunBackQuantity
		{
			get
			{
				return this._RunBackQuantity;
			}
			set
			{
				if ((this._RunBackQuantity != value))
				{
					this.OnRunBackQuantityChanging(value);
					this.SendPropertyChanging();
					this._RunBackQuantity = value;
					this.SendPropertyChanged("RunBackQuantity");
					this.OnRunBackQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunBackPrice", DbType="Decimal NOT NULL")]
		public decimal RunBackPrice
		{
			get
			{
				return this._RunBackPrice;
			}
			set
			{
				if ((this._RunBackPrice != value))
				{
					this.OnRunBackPriceChanging(value);
					this.SendPropertyChanging();
					this._RunBackPrice = value;
					this.SendPropertyChanged("RunBackPrice");
					this.OnRunBackPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this.OnInsertedByChanging(value);
					this.SendPropertyChanging();
					this._InsertedBy = value;
					this.SendPropertyChanged("InsertedBy");
					this.OnInsertedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InsertedOn
		{
			get
			{
				return this._InsertedOn;
			}
			set
			{
				if ((this._InsertedOn != value))
				{
					this.OnInsertedOnChanging(value);
					this.SendPropertyChanging();
					this._InsertedOn = value;
					this.SendPropertyChanged("InsertedOn");
					this.OnInsertedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Task.tbOp")]
	public partial class tbOp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaskCode;
		
		private short _OperationNumber;
		
		private string _UserId;
		
		private short _OpTypeCode;
		
		private short _OpStatusCode;
		
		private string _Operation;
		
		private string _Note;
		
		private System.DateTime _StartOn;
		
		private System.DateTime _EndOn;
		
		private decimal _Duration;
		
		private short _OffsetDays;
		
		private string _InsertedBy;
		
		private System.DateTime _InsertedOn;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskCodeChanging(string value);
    partial void OnTaskCodeChanged();
    partial void OnOperationNumberChanging(short value);
    partial void OnOperationNumberChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnOpTypeCodeChanging(short value);
    partial void OnOpTypeCodeChanged();
    partial void OnOpStatusCodeChanging(short value);
    partial void OnOpStatusCodeChanged();
    partial void OnOperationChanging(string value);
    partial void OnOperationChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnStartOnChanging(System.DateTime value);
    partial void OnStartOnChanged();
    partial void OnEndOnChanging(System.DateTime value);
    partial void OnEndOnChanged();
    partial void OnDurationChanging(decimal value);
    partial void OnDurationChanged();
    partial void OnOffsetDaysChanging(short value);
    partial void OnOffsetDaysChanged();
    partial void OnInsertedByChanging(string value);
    partial void OnInsertedByChanged();
    partial void OnInsertedOnChanging(System.DateTime value);
    partial void OnInsertedOnChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tbOp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaskCode
		{
			get
			{
				return this._TaskCode;
			}
			set
			{
				if ((this._TaskCode != value))
				{
					this.OnTaskCodeChanging(value);
					this.SendPropertyChanging();
					this._TaskCode = value;
					this.SendPropertyChanged("TaskCode");
					this.OnTaskCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationNumber", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short OperationNumber
		{
			get
			{
				return this._OperationNumber;
			}
			set
			{
				if ((this._OperationNumber != value))
				{
					this.OnOperationNumberChanging(value);
					this.SendPropertyChanging();
					this._OperationNumber = value;
					this.SendPropertyChanged("OperationNumber");
					this.OnOperationNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTypeCode", DbType="SmallInt NOT NULL")]
		public short OpTypeCode
		{
			get
			{
				return this._OpTypeCode;
			}
			set
			{
				if ((this._OpTypeCode != value))
				{
					this.OnOpTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._OpTypeCode = value;
					this.SendPropertyChanged("OpTypeCode");
					this.OnOpTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpStatusCode", DbType="SmallInt NOT NULL")]
		public short OpStatusCode
		{
			get
			{
				return this._OpStatusCode;
			}
			set
			{
				if ((this._OpStatusCode != value))
				{
					this.OnOpStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._OpStatusCode = value;
					this.SendPropertyChanged("OpStatusCode");
					this.OnOpStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this.OnOperationChanging(value);
					this.SendPropertyChanging();
					this._Operation = value;
					this.SendPropertyChanged("Operation");
					this.OnOperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartOn", DbType="DateTime NOT NULL")]
		public System.DateTime StartOn
		{
			get
			{
				return this._StartOn;
			}
			set
			{
				if ((this._StartOn != value))
				{
					this.OnStartOnChanging(value);
					this.SendPropertyChanging();
					this._StartOn = value;
					this.SendPropertyChanged("StartOn");
					this.OnStartOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndOn", DbType="DateTime NOT NULL")]
		public System.DateTime EndOn
		{
			get
			{
				return this._EndOn;
			}
			set
			{
				if ((this._EndOn != value))
				{
					this.OnEndOnChanging(value);
					this.SendPropertyChanging();
					this._EndOn = value;
					this.SendPropertyChanged("EndOn");
					this.OnEndOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Decimal NOT NULL")]
		public decimal Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffsetDays", DbType="SmallInt NOT NULL")]
		public short OffsetDays
		{
			get
			{
				return this._OffsetDays;
			}
			set
			{
				if ((this._OffsetDays != value))
				{
					this.OnOffsetDaysChanging(value);
					this.SendPropertyChanging();
					this._OffsetDays = value;
					this.SendPropertyChanged("OffsetDays");
					this.OnOffsetDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this.OnInsertedByChanging(value);
					this.SendPropertyChanging();
					this._InsertedBy = value;
					this.SendPropertyChanged("InsertedBy");
					this.OnInsertedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InsertedOn
		{
			get
			{
				return this._InsertedOn;
			}
			set
			{
				if ((this._InsertedOn != value))
				{
					this.OnInsertedOnChanging(value);
					this.SendPropertyChanging();
					this._InsertedOn = value;
					this.SendPropertyChanged("InsertedOn");
					this.OnInsertedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Task.vwDoc")]
	public partial class vwDocTaskCode
	{
		
		private string _EmailAddress;
		
		private string _TaskCode;
		
		private short _TaskStatusCode;
		
		private string _TaskStatus;
		
		private string _ContactName;
		
		private string _NickName;
		
		private string _UserName;
		
		private string _AccountName;
		
		private string _InvoiceAddress;
		
		private string _DeliveryAccountName;
		
		private string _DeliveryAddress;
		
		private string _CollectionAccountName;
		
		private string _CollectionAddress;
		
		private string _AccountCode;
		
		private string _TaskNotes;
		
		private string _ActivityCode;
		
		private System.DateTime _ActionOn;
		
		private string _UnitOfMeasure;
		
		private decimal _Quantity;
		
		private string _TaxCode;
		
		private System.Nullable<decimal> _TaxRate;
		
		private decimal _UnitCharge;
		
		private decimal _TotalCharge;
		
		private string _MobileNumber;
		
		private System.Data.Linq.Binary _Signature;
		
		private string _TaskTitle;
		
		private System.DateTime _PaymentOn;
		
		private string _SecondReference;
		
		private string _PaymentTerms;
		
		public vwDocTaskCode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(255)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TaskCode
		{
			get
			{
				return this._TaskCode;
			}
			set
			{
				if ((this._TaskCode != value))
				{
					this._TaskCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskStatusCode", DbType="SmallInt NOT NULL")]
		public short TaskStatusCode
		{
			get
			{
				return this._TaskStatusCode;
			}
			set
			{
				if ((this._TaskStatusCode != value))
				{
					this._TaskStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskStatus", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TaskStatus
		{
			get
			{
				return this._TaskStatus;
			}
			set
			{
				if ((this._TaskStatus != value))
				{
					this._TaskStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(100)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="NVarChar(100)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this._NickName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceAddress", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceAddress
		{
			get
			{
				return this._InvoiceAddress;
			}
			set
			{
				if ((this._InvoiceAddress != value))
				{
					this._InvoiceAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryAccountName", DbType="NVarChar(255)")]
		public string DeliveryAccountName
		{
			get
			{
				return this._DeliveryAccountName;
			}
			set
			{
				if ((this._DeliveryAccountName != value))
				{
					this._DeliveryAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryAddress", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DeliveryAddress
		{
			get
			{
				return this._DeliveryAddress;
			}
			set
			{
				if ((this._DeliveryAddress != value))
				{
					this._DeliveryAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionAccountName", DbType="NVarChar(255)")]
		public string CollectionAccountName
		{
			get
			{
				return this._CollectionAccountName;
			}
			set
			{
				if ((this._CollectionAccountName != value))
				{
					this._CollectionAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectionAddress", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string CollectionAddress
		{
			get
			{
				return this._CollectionAddress;
			}
			set
			{
				if ((this._CollectionAddress != value))
				{
					this._CollectionAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string AccountCode
		{
			get
			{
				return this._AccountCode;
			}
			set
			{
				if ((this._AccountCode != value))
				{
					this._AccountCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TaskNotes
		{
			get
			{
				return this._TaskNotes;
			}
			set
			{
				if ((this._TaskNotes != value))
				{
					this._TaskNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ActivityCode
		{
			get
			{
				return this._ActivityCode;
			}
			set
			{
				if ((this._ActivityCode != value))
				{
					this._ActivityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionOn", DbType="DateTime NOT NULL")]
		public System.DateTime ActionOn
		{
			get
			{
				return this._ActionOn;
			}
			set
			{
				if ((this._ActionOn != value))
				{
					this._ActionOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitOfMeasure", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string UnitOfMeasure
		{
			get
			{
				return this._UnitOfMeasure;
			}
			set
			{
				if ((this._UnitOfMeasure != value))
				{
					this._UnitOfMeasure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal NOT NULL")]
		public decimal Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="Decimal")]
		public System.Nullable<decimal> TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this._TaxRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitCharge", DbType="Decimal NOT NULL")]
		public decimal UnitCharge
		{
			get
			{
				return this._UnitCharge;
			}
			set
			{
				if ((this._UnitCharge != value))
				{
					this._UnitCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCharge", DbType="Money NOT NULL")]
		public decimal TotalCharge
		{
			get
			{
				return this._TotalCharge;
			}
			set
			{
				if ((this._TotalCharge != value))
				{
					this._TotalCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="NVarChar(50)")]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this._MobileNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signature", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Signature
		{
			get
			{
				return this._Signature;
			}
			set
			{
				if ((this._Signature != value))
				{
					this._Signature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTitle", DbType="NVarChar(100)")]
		public string TaskTitle
		{
			get
			{
				return this._TaskTitle;
			}
			set
			{
				if ((this._TaskTitle != value))
				{
					this._TaskTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentOn", DbType="DateTime NOT NULL")]
		public System.DateTime PaymentOn
		{
			get
			{
				return this._PaymentOn;
			}
			set
			{
				if ((this._PaymentOn != value))
				{
					this._PaymentOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondReference", DbType="NVarChar(20)")]
		public string SecondReference
		{
			get
			{
				return this._SecondReference;
			}
			set
			{
				if ((this._SecondReference != value))
				{
					this._SecondReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerms", DbType="NVarChar(100)")]
		public string PaymentTerms
		{
			get
			{
				return this._PaymentTerms;
			}
			set
			{
				if ((this._PaymentTerms != value))
				{
					this._PaymentTerms = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Invoice.vwDocTask")]
	public partial class vwDocInvoiceTask
	{
		
		private string _InvoiceNumber;
		
		private string _TaskCode;
		
		private string _TaskTitle;
		
		private string _ActivityCode;
		
		private string _CashCode;
		
		private string _CashDescription;
		
		private System.Nullable<System.DateTime> _ActionedOn;
		
		private decimal _Quantity;
		
		private string _UnitOfMeasure;
		
		private decimal _InvoiceValue;
		
		private decimal _TaxValue;
		
		private string _TaxCode;
		
		private string _SecondReference;
		
		public vwDocInvoiceTask()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TaskCode
		{
			get
			{
				return this._TaskCode;
			}
			set
			{
				if ((this._TaskCode != value))
				{
					this._TaskCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTitle", DbType="NVarChar(100)")]
		public string TaskTitle
		{
			get
			{
				return this._TaskTitle;
			}
			set
			{
				if ((this._TaskTitle != value))
				{
					this._TaskTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ActivityCode
		{
			get
			{
				return this._ActivityCode;
			}
			set
			{
				if ((this._ActivityCode != value))
				{
					this._ActivityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CashCode
		{
			get
			{
				return this._CashCode;
			}
			set
			{
				if ((this._CashCode != value))
				{
					this._CashCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashDescription", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CashDescription
		{
			get
			{
				return this._CashDescription;
			}
			set
			{
				if ((this._CashDescription != value))
				{
					this._CashDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActionedOn
		{
			get
			{
				return this._ActionedOn;
			}
			set
			{
				if ((this._ActionedOn != value))
				{
					this._ActionedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal NOT NULL")]
		public decimal Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitOfMeasure", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string UnitOfMeasure
		{
			get
			{
				return this._UnitOfMeasure;
			}
			set
			{
				if ((this._UnitOfMeasure != value))
				{
					this._UnitOfMeasure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceValue", DbType="Money NOT NULL")]
		public decimal InvoiceValue
		{
			get
			{
				return this._InvoiceValue;
			}
			set
			{
				if ((this._InvoiceValue != value))
				{
					this._InvoiceValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxValue", DbType="Money NOT NULL")]
		public decimal TaxValue
		{
			get
			{
				return this._TaxValue;
			}
			set
			{
				if ((this._TaxValue != value))
				{
					this._TaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="NVarChar(10)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this._TaxCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondReference", DbType="NVarChar(20)")]
		public string SecondReference
		{
			get
			{
				return this._SecondReference;
			}
			set
			{
				if ((this._SecondReference != value))
				{
					this._SecondReference = value;
				}
			}
		}
	}
	
	public partial class proc_OpResult
	{
		
		private string _TaskCode;
		
		private short _OperationNumber;
		
		private short _SyncTypeCode;
		
		private short _OpStatusCode;
		
		private string _UserId;
		
		private string _Operation;
		
		private string _Note;
		
		private System.DateTime _StartOn;
		
		private System.DateTime _EndOn;
		
		private short _OffsetDays;
		
		private string _InsertedBy;
		
		private System.DateTime _InsertedOn;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
		private System.Data.Linq.Binary _RowVer;
		
		private System.Nullable<decimal> _Duration;
		
		public proc_OpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TaskCode
		{
			get
			{
				return this._TaskCode;
			}
			set
			{
				if ((this._TaskCode != value))
				{
					this._TaskCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationNumber", DbType="SmallInt NOT NULL")]
		public short OperationNumber
		{
			get
			{
				return this._OperationNumber;
			}
			set
			{
				if ((this._OperationNumber != value))
				{
					this._OperationNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncTypeCode", DbType="SmallInt NOT NULL")]
		public short SyncTypeCode
		{
			get
			{
				return this._SyncTypeCode;
			}
			set
			{
				if ((this._SyncTypeCode != value))
				{
					this._SyncTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpStatusCode", DbType="SmallInt NOT NULL")]
		public short OpStatusCode
		{
			get
			{
				return this._OpStatusCode;
			}
			set
			{
				if ((this._OpStatusCode != value))
				{
					this._OpStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this._Operation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartOn", DbType="DateTime NOT NULL")]
		public System.DateTime StartOn
		{
			get
			{
				return this._StartOn;
			}
			set
			{
				if ((this._StartOn != value))
				{
					this._StartOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndOn", DbType="DateTime NOT NULL")]
		public System.DateTime EndOn
		{
			get
			{
				return this._EndOn;
			}
			set
			{
				if ((this._EndOn != value))
				{
					this._EndOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffsetDays", DbType="SmallInt NOT NULL")]
		public short OffsetDays
		{
			get
			{
				return this._OffsetDays;
			}
			set
			{
				if ((this._OffsetDays != value))
				{
					this._OffsetDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this._InsertedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedOn", DbType="DateTime NOT NULL")]
		public System.DateTime InsertedOn
		{
			get
			{
				return this._InsertedOn;
			}
			set
			{
				if ((this._InsertedOn != value))
				{
					this._InsertedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowVer", DbType="rowversion NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary RowVer
		{
			get
			{
				return this._RowVer;
			}
			set
			{
				if ((this._RowVer != value))
				{
					this._RowVer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
